#!/bin/sh

lock() {
	gnome-screensaver-command -l
}

case $1 in
	lock)
		lock
		;;
	suspend)
		systemctl suspend && lock
		;;
	hibernate)
		systemctl hibernate && lock
		;;
	exit)
		i3-msg exit
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
		echo "Usage: $0 {lock|suspend|hibernate|exit|reboot|shutdown}"
		exit 2
esac

exit 0
